Paginated history entry 1006
xtdb/xtdb pull request #1068
Opened 2020-08-28 08:07 UTC by rhinocratic

Added options `limit` (number of items per page) and `resume-history-from` (transaction id of the first item in a page of history) to the options for requesting entity histories.

The header of the response to a history request contains a `Link` header with `rel=next` containing the URL of the next page.  Any history options contained in the original request are propagated to the link, as is the latest transaction time upon receipt of the first page request.

2020-08-28 09:26 UTC, jarohen requested changes
Thanks @rhinocratic

Unfortunately the test (and hence, I'm fairly sure, the underlying code) doesn't cover the case we talked about - entity history returns the history of the entity sorted first by valid time and then by transaction time. In this case, the test's inserting data where valid-time is (almost) the same as transaction-time and there are no two entities with the same valid-time - so the second half of the sort isn't exercised.

We talked about an example where there was multiple revisions (throughout transaction-time) at each valid-time - say, ten transactions (let's call them tt 0 through 9) each submitting a single entity at ten different valid times (vt 0 through 9). If you were to make an entity history request, ascending, limit 15, you'd expect to see the first ten entries be vt 0, tt 0 through 9; the remaining 5 at vt 1, tt 0 through 4. At this point, the next page has start vt 1 (we update the start vt because it's the first entry in the sort order), start tt unbounded (because it's the second entry - we don't want vt 2 to have start tt 4), resume tx-id 4.

2020-08-28 12:00 UTC, rhinocratic commented
I've changed the tests to send batches of transactions, where the valid time for successive batches cycles through a predefined list.  There's a minor change to the URL building in entity.clj, but the method seems to return the expected results.

2020-09-02 08:21 UTC, danmason approved these changes
WIll need a separate push of work to fix it on the console (currently displays blank), but otherwise approved.

2020-09-08 09:22 UTC, jarohen commented
Have merged the streaming changes in separately as #1075, will park the pagination changes temporarily while we're making other changes to that API, and then look to re-incorporate this PR.

2020-09-08 09:22 UTC, closed without merging