HTTP JSON API (Draft)
xtdb/xtdb pull request #1150
Opened 2020-10-02 15:58 UTC by danmason

Still a work in progress, resolves #284 

Currently based on #1139, #1142 and #1145

2020-10-13 13:03 UTC, jarohen commented
> - Figure out what to do with entity-refs
'just' return the eids, as if link-entities is a no-op for JSON reqs

> - Investigate using spec-tools for conforming parsed JSON (doing `put` -> `:crux.tx/put`, handling dates etc - rather than doing these transformations in muuntaja)
tbc, will read through the PR

> - Need to document behaviour somewhere
tabs on the docs for now, we'll add Swagger/OpenAPI later (#1110)

2020-10-15 16:38 UTC, jarohen commented on crux-http-server/src/crux/http_server/util.clj
> +(defn crux-object-mapper [{:keys [camel-case? mapper-options] :as options}]
think this will indiscriminately convert keys to camelCase, even within users' documents?

2020-10-19 10:15 UTC, jarohen requested changes
As discussed, on the docs:
* 'All of the REST endpoints return both EDN and Transit' - do they all return JSON now?
* Should the JSON request tabs pass their QPs in camelCase? In fact, do we need a generic note about kebab-case/camelCase...?
* entity-history 
  * missing `eid-json` in required params
  * 'under the `:crux.db/doc` key' - in fact, a few mentions of `crux.tx`, which doesn't apply to JSON
* entity-tx 
  * `eid-json` in required params
  * JSON tab shouldn't use `eid-edn` - just `eid`? (probably applies elsewhere as well)
* query
  * Shouldn't be two `#query` IDs - `#get-query` and `#post-query`?
  * `POST /_crux/query` doesn't accept a JSON body - worth an NB
  * `?query` QP (in hindsight) should be `?query-edn` - are there any more?
* submit-tx - this assumes the JSON reader is already familiar with the Clojure API - we're hoping they won't need to be.
* sync - 'timeout defaulting to 10s' - sure? thought it was 30.

2020-10-19 13:48 UTC, jarohen commented
@danmason - @hraberg's introducing a `#crux/base64` reader macro with #1168 - we'll want to encode byte arrays to print this reader macro when that PR's merged. Depends which one's merged first :)

2020-10-19 13:49 UTC, danmason commented
Should hopefully be as simple as adding a custom encoder!

2020-10-20 09:59 UTC, danmason commented on crux-http-server/src/crux/http_server/query.clj
> +;; TODO: Need to ensure all query clauses are present + coerced properly
Likely a redundant TODO - all clauses would be present + coerced when passed into `query-edn`

2020-10-20 10:09 UTC, jarohen approved these changes
Nice work @danmason, great to see :)

2020-10-20 10:40 UTC, hraberg approved these changes
Looks good, tried to grok if there's a JSON date encoder, or is this provided by default.?

Also, not 100% sure about the nested types in JSON (as opposed to just strings), but we can iterate this. The "oid" concept isn't used elsewhere in Crux.

2020-10-20 17:20 UTC, merged