Added failing tests for Java Map IDs
xtdb/xtdb pull request #1397
Opened 2021-01-25 14:49 UTC by AlistairONeill

Using `java.util.Map` as a CruxID is broken. This PR adds tests to check that they work as intended when the fix is implemented.

2021-01-27 17:12 UTC, jarohen commented
thanks for these :smile: mind including them with the other related tests, `tx_test.clj` `map-ordering-362` and `incomparable-colls-1001`?

(might well only be the former)

2021-01-27 17:12 UTC, jarohen requested changes
thanks for these :smile: mind including them with the other related tests, `tx_test.clj` `map-ordering-362` and `incomparable-colls-1001`?

(might well only be the former)

2021-01-28 14:21 UTC, AlistairONeill commented
Moved to `tx-test`

2021-01-29 13:59 UTC, AlistairONeill commented
Failed Test: https://app.circleci.com/pipelines/github/juxt/crux/1838/workflows/b2348fa6-7fe7-473a-9631-1615148aa2e5/jobs/7104

It looks like this one fails intermittently as I haven't touched any of the code only added extra tests so can't have slowed anything down crux wise

2021-05-25 18:32 UTC, jarohen commented
Merged in 8d8e6a54e567aeade8372e99f0409ae1de352fec, thanks @AlistairONeill :pray:

2021-05-25 18:32 UTC, closed without merging