Support multiple Lucene stores via pred opts map with :lucene-store-k
xtdb/xtdb pull request #1577
Opened 2021-07-23 22:21 UTC by refset

Enabled by the recent secondary indexes changes https://github.com/juxt/crux/pull/1555

2021-07-23 22:24 UTC, refset commented on crux-lucene/src/crux/lucene.clj
> +                        ;; Used for eviction
Added for completeness - but correct me if I'm wrong!

2021-07-23 22:26 UTC, refset commented on crux-lucene/src/crux/lucene/multi_field.clj
> -  (s/cat :pred-fn #{'lucene-text-search} :args (s/spec (s/cat :query (some-fn string? symbol?) :bindings (s/* :crux.query/binding))) :return (s/? :crux.query/binding)))
I'm fairly sure `:crux.query/binding` wasn't right here, since it covers more than just logic-vars.

2021-07-23 22:27 UTC, refset commented on crux-lucene/src/crux/lucene/multi_field.clj
> +  (s/cat :pred-fn #{'lucene-text-search} :args (s/spec (s/cat :query (some-fn string? q/logic-var?) :bindings (s/* (some-fn string? q/logic-var?)) :opts (s/? (some-fn map? q/logic-var?)))) :return (s
I added `string?` since it's free and useful.

2021-07-23 22:29 UTC, refset commented on crux-lucene/test/crux/lucene/extension_test.clj
> +  (:require  [clojure.test :as t]
ah, I left more requires than strictly needed here, but I will make use of them in the next PR

2021-07-24 14:02 UTC, jarohen requested changes
Nice one @refset - couple of small suggestions but otherwise good to go :smile:

2021-07-24 14:02 UTC, jarohen commented on crux-lucene/test/crux/lucene/extension_test.clj
> +    (c/await-tx n (c/submit-tx n [[:crux.tx/put {:crux.db/id :ivan
nit: submit+await-tx 🙂

2021-07-24 14:02 UTC, jarohen commented on crux-lucene/src/crux/lucene.clj
> +                           lucene-store)
A pattern I've seen for this kind of situation (i.e. where you're picking off optional args one at a time) is using tuple destructuring in a multiple-return sort of way:

```clojure
(let [last-arg (last arg-bindings)
      [arg-bindings {:keys [lucene-store-k] :as opts}] (if (map? last-arg)
                                                         [(butlast arg-bindings) last-arg]
                                                         [arg-bindings nil])
      lucene-store (or (get pred-ctx lucene-store-k)
                       lucene-store)]
  )
```

2021-07-24 14:02 UTC, jarohen commented on crux-lucene/src/crux/lucene.clj
> +                           lucene-store)
Also, maybe slightly cleaner if you don't destructure `::lucene-store` out at the top?

```clojure
(let [last-arg (last arg-bindings)
      [arg-bindings opts] (if (map? last-arg)
                            [(butlast arg-bindings) (last arg-bindings)]
                            [arg-bindings nil])
      lucene-store (get pred-ctx (or (:lucene-store-k opts) ::lucene-store))]
  )
```

2021-07-26 11:35 UTC, refset commented on crux-lucene/src/crux/lucene.clj
> +                           lucene-store)
nice suggestions, thanks!

2021-07-26 16:05 UTC, merged