Jan/healthcheck
xtdb/xtdb pull request #1895
Opened 2023-02-08 10:40 UTC by jsulmont

* fix #1867

2023-02-10 09:41 UTC, jarohen commented on docs/extensions/modules/ROOT/pages/health-server.adoc
> +// TODO finish this write-up once I've sorted the event question.
still applicable?

2023-02-10 10:02 UTC, jarohen requested changes
cheers @jsulmont - looking good, minor feedback as always :smile: aware you said you're still working on the docs so I haven't reviewed those in detail, but they're looking promising.

2023-02-10 10:02 UTC, jarohen commented on modules/http-health-check/README.adoc
> +.deps.ednxxx
xxx?

2023-02-10 10:02 UTC, jarohen commented on modules/http-health-check/project.clj
> +                 [compojure "1.7.0"]]
We use the reitit stack in the main HTTP server - any reason to differ here?

Also, we're hosted on Maven Central so we can only use other deps already on Central (i.e. not on Clojars) - we have mirrored most of the HTTP stack already which you can likely reuse here - see the http-server project.clj.

2023-02-10 10:02 UTC, jarohen commented on resources/logback-test.xml
> +  <root level="INFO">
just to check - was this intentional?

2023-02-10 10:02 UTC, jarohen commented on core/src/xtdb/bus.clj
> +    :namespace ~(str *ns*)
do we necessarily want to couple these events to the actual XT namespaces? it makes what's essentially an impl detail part of the public API.

although maybe they already are, because of the module keys in the config. :thinking:

2023-02-10 10:02 UTC, jarohen commented on modules/http-health-check/src/xtdb/http_health_check.clj
> +(defonce base-time (System/nanoTime))
should this be part of the node startup, rather than `defonce`? the node's lifecycle isn't necessarily tied to the JVM (although most people probably use it that way) - it's technically a component. we have had questions in the past related to multi-tenanted XT nodes - users that manage multiple XT nodes that come and go within one JVM process, for data isolation purposes.

2023-02-10 10:02 UTC, jarohen commented on modules/http-health-check/src/xtdb/http_health_check.clj
> +(defonce base-time (System/nanoTime))
also, do we need a separate timestamp and nano-time? I understand you probably want to use nano-time for elapsed time since the start of the node, but maybe an Instant (with microseconds, in practice) has enough granularity for both?

2023-02-10 10:02 UTC, jarohen commented on modules/http-health-check/README.adoc
> += xtdb-http-server
this file looks like it's meant to be for the health check, but is a straight copy of the HTTP one?

2023-02-10 10:35 UTC, jsulmont commented on modules/http-health-check/src/xtdb/http_health_check.clj
> +(defonce base-time (System/nanoTime))
It doesn't really matter when this base-time is initialised as long as it's only initialised once per XT (works fine when multiple XT nodes share the same JVM). Indeed that `base-time` is just used as a ... base time against which subsequent calls to `System/nanoTime` will be related. 
The `:clock` attribute, is (hopefully) monotonic -- I find a double easier to look at, than a timestamp.
Note that the `event` map already has a `:timestamp` attribute, which receives whatever `java.util.Date.` will return (that is, accurate to the millisecond). 
This is entirely subjective and I am happy to get rid of it altogether -- please let me know.
PS note that Criterium  is using `System/nanoTime`.

2023-02-10 10:42 UTC, jsulmont commented on core/src/xtdb/bus.clj
> +    :namespace ~(str *ns*)
I thought that would make the life of users easier. The HTTP serves a `/healthz/ns/:ns` route that allows to fetch events of the said namespace. Also a GET on `/healthz` simply returns the `last` event of each namespace.
XT namespaces encapsulate related parts (e.g., `node` `checkpoint` `tx` ...) and I thought it'd be nice for a user to be able to inspect them. A good example, is the checkpointing, which runs its own thread -- yet is able to seriously impact the overall function of the node.

2023-02-10 10:42 UTC, jsulmont commented on resources/logback-test.xml
> +  <root level="INFO">
Nope sorry!

2023-02-10 10:50 UTC, jsulmont commented on modules/http-health-check/project.clj
> +                 [compojure "1.7.0"]]
No reason, other than I've never used the reitit stack and found compojure way.

Also the dependencies embarked by the http-server are *heavy*, most of them totally useless for this tiny web server; 

Happy to move to reitit let me know. 🤷🏻

2023-02-10 11:50 UTC, jarohen commented on core/src/xtdb/bus.clj
> +    :namespace ~(str *ns*)
Yep - I agree with the categorisation, for the reasons you say, it was more about enforcing the coupling of categories to the impl namespaces. we could maybe use the namespace of the event-type keyword instead?

(just ideas/speculation, would be fine to merge as-is)

2023-02-10 11:54 UTC, jarohen commented on modules/http-health-check/src/xtdb/http_health_check.clj
> +(defonce base-time (System/nanoTime))
> I find a double easier to look at, than a timestamp.
yep, I understand - my comment above was suggesting that you could do this with `(- now base-instant)` (or, rather, the appropriate java.time method)

not a big deal - again, fine to merge as-is

2023-02-10 11:56 UTC, jsulmont commented on core/src/xtdb/bus.clj
> +    :namespace ~(str *ns*)
@jarohen I thought about it (in fact, I am doing that for internal events (i.e,  events where ::xt/event-type is not :healthz)
However for it to work correctly  that would require the event to be a namespaced kw  and I thought that would be too much of a restriction.

2023-02-10 11:57 UTC, jarohen commented on modules/http-health-check/project.clj
> +                 [compojure "1.7.0"]]
> No reason, other than I've never used the reitit stack and found compojure way.

cool - in that case, yeah, let's go with consistency

> Also the dependencies embarked by the http-server are heavy, most of them totally useless for this tiny web server

this is a fair point, and good to consider dependency weight - but if the user's using an XT-provided Docker image it'll already contain most of them, and chances are the startup time introduced by these deps will be pretty insignificant compared to restoring a checkpoint

2023-02-10 11:59 UTC, jsulmont commented on modules/http-health-check/project.clj
> +                 [compojure "1.7.0"]]
Thank you! I promised I'll get into reitit 👍🏻

2023-02-14 09:46 UTC, jarohen approved these changes
one cheeky `prn`, otherwise good to go - cheers @jsulmont! :pray:

2023-02-14 09:50 UTC, merged