Fixes #173 API call for full-results?
xtdb/xtdb pull request #197
Opened 2019-04-25 13:21 UTC by jonpither

2019-04-25 13:28 UTC, hraberg requested changes
Otherwise looks good. Can see the case for simpler keys as well.

2019-04-25 13:28 UTC, hraberg commented on test/crux/api_test.clj
> +                (t/is (= '([{:var e, :value :ivan, :doc {:crux.db/id :ivan, :name "Ivan"}}]) result))
For consistency with other APIs we probably want name spaced keys here, like `crux.query/var` or similar.

2019-04-29 18:54 UTC, hraberg approved these changes
Cool, might prefer full keys rather than relying on double-colon in case someone moves the function to another namespace, but there's a test, so let's merge.

2019-04-29 18:54 UTC, merged

2019-04-29 18:56 UTC, jonpither commented
Fair enough @hraberg, will tidy this up in a subsequent commit