Fix LeafMergeQueue for non-consecutive ordinals
xtdb/xtdb pull request #2715
Opened 2023-08-23 10:21 UTC by FiV0

2023-08-23 11:32 UTC, FiV0 commented on core/src/main/java/xtdb/trie/LeafMergeQueue.java
>      private final PriorityQueue<LeafPointer> pq;
Realized during Standup that we could also just maintain a map from <ordinal, ivectorreader>.

2023-08-23 12:25 UTC, FiV0 commented on core/src/main/java/xtdb/trie/LeafMergeQueue.java
>      private final PriorityQueue<LeafPointer> pq;
Addressed.

2023-08-23 17:31 UTC, jarohen requested changes
Nice one @FiV0, good spot 👏

We probably don't want to be doing map lookups here if we can avoid it - would a sparse array work instead?

2023-08-24 07:30 UTC, FiV0 commented
@jarohen which of the two map lookups? I am assuming the Clojure one.

2023-08-24 11:00 UTC, merged