Update docs to use symbols in :args, relates to #247
xtdb/xtdb pull request #282
Opened 2019-07-02 15:50 UTC by Antonelli712

Updated the docs examples to use symbol instead of keywords in the interest of clearer examples.

2019-07-03 13:42 UTC, refset commented on docs/queries.adoc
> + :args [{'my-offset 990}]}
We should quote the outer vecs for `:where` `:find` and `:order-by` as well.

2019-07-03 13:44 UTC, refset commented on docs/queries.adoc
> + :args [{'?e1 :1}]
I don't think we need to quote this particular instance at all.

2019-07-03 13:46 UTC, refset requested changes
@Antonelli712 a couple of small changes but otherwise looks good to go :+1:

2019-07-04 09:31 UTC, Antonelli712 commented
Changes made, and updated all quotes for continuity.

2019-07-08 08:47 UTC, merged