Add support for regclass and current_schemas()
xtdb/xtdb pull request #3559
Opened 2024-08-05 11:51 UTC by mbutlerw

2024-08-05 13:14 UTC, jarohen requested changes
* schema moving to watermark, make it consistent
* empty watermark for tests to remove the nil-handling in real code
* zero the first bit of/abs the oid after hashing it to avoid unsigned/signed issues
* create a `current-schemas` fn outside of the codegen (see expr.temporal)

2024-08-05 13:14 UTC, jarohen commented on core/src/main/kotlin/xtdb/operator/IProjectionSpec.kt
> +    fun project(allocator: BufferAllocator, readRelation: RelationReader, schema: IPersistentMap, params: RelationReader): IVectorReader
IPM -> `Map`

2024-08-05 13:14 UTC, jarohen commented on core/src/main/clojure/xtdb/expression/pg.clj
> +(def search-path
"xt" too?

2024-08-05 13:14 UTC, jarohen commented on core/src/main/clojure/xtdb/expression/pg.clj
> +   #(do
```clojure
(fn [[rc-code]]
  ...)
```

2024-08-05 13:14 UTC, jarohen commented on core/src/main/clojure/xtdb/expression/pg.clj
> +        (if-let [tn# (get-in ~expr/schema-sym [:oid->table oid#])]
indentation

2024-08-05 13:14 UTC, jarohen commented on core/src/main/clojure/xtdb/expression/pg.clj
> +   :->call-code #(do `(do ~@%))})
`first`

2024-08-28 10:33 UTC, mbutlerw commented
Closing in favour off separate PRs which bring in the above changes in a more incremental way.

See https://github.com/xtdb/xtdb/pull/3646 for regclass.

2024-08-28 10:33 UTC, closed without merging