Add Bitwise Operators
xtdb/xtdb pull request #3719
Opened 2024-09-19 18:14 UTC by Akeboshiwind

Fixes #3714

2024-09-19 20:32 UTC, jarohen requested changes
Nice one @Akeboshiwind :clap: just some pedantry around the type widening, otherwise good to go

2024-09-19 20:32 UTC, jarohen commented on core/src/main/clojure/xtdb/expression.clj
> +  (let [return-type (types/least-upper-bound arg-types)]
with bit-not, you don't need the LUB of the arg-types - there's only one.

2024-09-19 20:32 UTC, jarohen commented on core/src/main/clojure/xtdb/expression.clj
> +  (let [return-type (types/least-upper-bound arg-types)]
I'd be tempted (but check Postgres) to just use the type of the left-hand argument here - the difference it makes is in overflow handling.

edit: checked Postgres: `SELECT 1::smallint << 16::int;` => 0; I'd guess it gives 2^16 for us as it stands?

2024-09-23 16:53 UTC, Akeboshiwind commented
As discussed on Slack it turns out Postgres does weird things with the shift operators:

```
SELECT 3::smallint << 16; => 0
SELECT 3::smallint << 32; => 3
SELECT 3::smallint << 31; => 0

SELECT 3::int << 32; => 3
SELECT 3::int << 31; => -2147483648

SELECT 3::int << 38; => 48
SELECT 3::int << 12 << 12 << 12; => 0
```

Basically it looks like Postgres does `mod(n, 32)` on the rhs.

We decided to leave this as the JVM default for now until some tool eventually requires it 😅

2024-09-24 09:23 UTC, merged