rewrite != to <> in lexer #3773
xtdb/xtdb pull request #3778
Opened 2024-10-10 14:40 UTC by mpisanko

2024-10-10 14:40 UTC, mpisanko commented
would u pls have a look @mbutlerw

2024-10-10 14:46 UTC, mbutlerw submitted a review, later dismissed

2024-10-10 14:54 UTC, mbutlerw requested changes
Change looks good overall, but could we add a test for this if there isn't already coverage.

2024-10-11 10:27 UTC, mbutlerw approved these changes

2024-10-18 14:51 UTC, jarohen requested changes
@mpisanko I know this is a three-liner, but I'd probably fix this in plan.clj (something like `((some-fn {'!= '<>} identity) (symbol (.getText (.compOp ctx))))` in `visitComparisonPredicate{,Part2}`?), or maybe as an alias in the expression engine - reason being I think this _may_ alter any error messages, changing the user's original query...?

2024-10-21 13:06 UTC, jarohen approved these changes

2024-10-21 13:06 UTC, merged