Catch ArithmeticException at EE boundary
xtdb/xtdb pull request #3807
Opened 2024-10-18 16:08 UTC by FiV0

This catches `ArithmeticException`s at the Expression Engine boundary and turns them into runtime exceptions so that we don't fall over in the indexer.

2024-10-18 17:33 UTC, jarohen requested changes

2024-10-18 17:33 UTC, jarohen commented on core/src/main/clojure/xtdb/expression.clj
> +    (prn message)
cheeky prn

2024-10-18 17:33 UTC, jarohen commented on core/src/main/clojure/xtdb/expression.clj
> +                                          (catch ArithmeticException e#
probably needn't include this in the code generation - just outside should suffice?

2024-10-21 13:44 UTC, FiV0 commented
@jarohen I added another commit for non fitting decimals. Maybe you can have look if the catching at that level seems suspicious.

2024-10-22 08:54 UTC, jarohen commented on core/src/main/clojure/xtdb/expression.clj
> +              (catch ArithmeticException e#
don't need the gensym here now you're out of macro-land

2024-10-22 08:54 UTC, jarohen approved these changes

2024-10-23 15:44 UTC, merged