add elixir lang test - uses binary encoding
xtdb/xtdb pull request #3830
Opened 2024-11-01 12:32 UTC by mpisanko

2024-11-01 14:40 UTC, FiV0 requested changes
Just two tiny remarks otherwise LGTM.

2024-11-01 14:40 UTC, FiV0 commented on lang/elixr/lib/elixr.ex
> +end
What is this file for?

2024-11-01 14:40 UTC, FiV0 commented on core/src/main/clojure/xtdb/types.clj
> +                            (20 1016) [8 (fn [bb ^long start ^long typlen ^long idx] (.getLong bb (+ start (* idx typlen))))])
These function still has reflection warnings on the `.getInt` and `.getLong`.

2024-11-05 12:21 UTC, mpisanko commented on lang/elixr/lib/elixr.ex
> +end
removed- not needed

2024-11-06 13:05 UTC, merged