Display tables
xtdb/xtdb pull request #3940
Opened 2024-12-03 16:05 UTC by mpisanko

2024-12-12 12:39 UTC, mpisanko commented
blocked by #3962

2024-12-30 14:14 UTC, mpisanko commented
This PR adds grammar required to use postgres compatible \d, 5\dt \d foo

2024-12-31 15:36 UTC, mpisanko commented
not really sure why the information_schema/pg_catalog tables are showing along the 'public' schema tables (so it appears):
```
mpi@mpimbp ~ [2]> psql -p 5432 -h localhost -U xtdb
psql (17.0, server 16)
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, compression: off, ALPN: none)
Type "help" for help.

xtdb=> \d
              List of relations
 Schema |        Name         | Type  | Owner
--------+---------------------+-------+-------
 public | columns             | table | xtdb
 public | foo                 | table | xtdb
 public | pg_am               | table | xtdb
 public | pg_attribute        | table | xtdb
 public | pg_class            | table | xtdb
 public | pg_database         | table | xtdb
 public | pg_description      | table | xtdb
 public | pg_matviews         | table | xtdb
 public | pg_namespace        | table | xtdb
 public | pg_proc             | table | xtdb
 public | pg_range            | table | xtdb
 public | pg_settings         | table | xtdb
 public | pg_stat_user_tables | table | xtdb
 public | pg_tables           | table | xtdb
 public | pg_type             | table | xtdb
 public | pg_user             | table | xtdb
 public | pg_views            | table | xtdb
 public | schemata            | table | xtdb
 public | tables              | table | xtdb
 public | txs                 | table | xtdb
(20 rows)
```

2025-01-02 08:55 UTC, FiV0 commented
> not really sure why the information_schema/pg_catalog tables are showing along the 'public' schema tables (so it appears):

I recently added metadata tables to metadata tables https://github.com/xtdb/xtdb/pull/3956. I suspect this is the reason they show up.

2025-01-02 09:20 UTC, FiV0 requested changes

2025-01-02 09:20 UTC, FiV0 commented on core/src/main/clojure/xtdb/information_schema.clj
> +             ;; FIXME this should prolly be something else (arrow-HMT-handler?)
Can we try to use correct spelling.

2025-01-02 09:20 UTC, FiV0 commented on core/src/main/clojure/xtdb/sql/plan.clj
> +    ;; TODO - apply collation
What does this mean? We are now parsing `COLLATE` but are not really applying the logic?

2025-01-02 09:20 UTC, FiV0 commented on core/src/main/clojure/xtdb/information_schema.clj
> +             ;; FIXME this should prolly be something else (arrow-HMT-handler?)
Likely `HAMTrie`

2025-01-02 11:01 UTC, mpisanko commented on core/src/main/clojure/xtdb/sql/plan.clj
> +    ;; TODO - apply collation
yeah - no idea what to do. in my understanding collation affects eg string ordering - but have no idea how and where to apply that. also - when trying to apply it - it might have to spread thru the system?

2025-01-03 09:44 UTC, mpisanko commented on core/src/main/clojure/xtdb/information_schema.clj
> +             ;; FIXME this should prolly be something else (arrow-HMT-handler?)
probably you mean `prolly`? it's kind of like i18n - so not really keen on changing that. sorry.

2025-01-03 16:26 UTC, FiV0 commented on core/src/main/clojure/xtdb/sql/plan.clj
> +    ;; TODO - apply collation
If a query is using `COLLATE` then it's likely expecting results in some order. I am not saying we need to fully implement it, but it would be good to understand why a query is using `COLLATE` and then decide if or if not to honor the meaning.

2025-01-04 11:52 UTC, mpisanko commented on core/src/main/clojure/xtdb/sql/plan.clj
> +    ;; TODO - apply collation
the query in this case is:
```sql
 SELECT c.oid,
  n.nspname,
  c.relname
FROM pg_catalog.pg_class c
     LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
WHERE c.relname OPERATOR(pg_catalog.~) '^(foo)$' COLLATE pg_catalog.default
  AND pg_catalog.pg_table_is_visible(c.oid)
ORDER BY 2, 3;
```
and default collation is used - so it would affect sort order - but given this is purely psql 'sugar' - think we can get away even in some cases when the tables are slightly 'misordered' (according to default collation)?
but then if users start using COLLATE - it might spell trouble. so maybe it should be documented that it's not supported?

2025-01-15 08:59 UTC, FiV0 commented on core/src/main/clojure/xtdb/sql/plan.clj
> +    ;; TODO - apply collation
But `foo` is just an example here, right? This currently wouldn't work for `FOO` even though that is what the "real" pg would also work with. I am not saying you need to implement it, but lets' document it somewhere. Preferably some top-level comment on this PR and link to it from that `TODO`.

2025-01-15 09:02 UTC, FiV0 commented on core/src/main/clojure/xtdb/sql/plan.clj
> +    ;; TODO - apply collation
If you want you can even open a new ticket for the feature `COLLATE` where you document what we currently do and what would need to happen to fully support `COLLATE`.

2025-01-15 09:43 UTC, mpisanko commented on core/src/main/clojure/xtdb/sql/plan.clj
> +    ;; TODO - apply collation
opened #4020 to implement COLLATE

2025-01-15 10:15 UTC, jarohen commented
prefer rebases to merges, please, and link PR to card :pray: 

https://github.com/xtdb/xtdb/blob/main/dev/GIT.adoc

2025-01-15 10:17 UTC, jarohen commented
https://github.com/xtdb/xtdb/pull/3940#issuecomment-2567446761

These should be in the `pg_catalog` schema - not urgent, but one we should card up?

2025-01-15 10:22 UTC, jarohen requested changes

2025-01-15 10:22 UTC, jarohen commented on core/src/main/antlr/xtdb/antlr/Sql.g4
> +    | exprPrimary '::' schemaName '.' 'REGTYPE' '::' schemaName '.' 'TEXT' # PgCatalogResolveOid
this looks like two distinct expressions? i.e. schemaName.regtype and `expr :: schema.text`?

in fact, the latter looks like it's standard cast syntax, so do we need to make that change there instead?

2025-01-15 10:22 UTC, jarohen commented on core/src/main/antlr/xtdb/antlr/SqlLexer.g4
> +PG_CATALOG_DEFAULT : 'pg_catalog.default' ;
I doubt this is a token in the language, unless we're going to specify every collation as a token - I suspect collation wants to be `(schemaName '.')? identifier`?

2025-01-15 10:22 UTC, jarohen commented on core/src/main/clojure/xtdb/information_schema.clj
> +                          relhasindex :bool, relhasrules :bool, relhastriggers :bool, relrowsecurity :bool
nit: indent

2025-01-15 10:22 UTC, jarohen commented on core/src/main/clojure/xtdb/information_schema.clj
> +             ;; FIXME this should prolly be something else (arrow-HAMTrie-handler?)
this is the sort of comment to either resolve beforehand, or explicitly decide not to handle now

2025-01-16 14:58 UTC, mpisanko commented on core/src/main/antlr/xtdb/antlr/Sql.g4
> +    | exprPrimary '::' schemaName '.' 'REGTYPE' '::' schemaName '.' 'TEXT' # PgCatalogResolveOid
right, but then - it's kind of context dependent: regtype can be an int or text (which is the typename - so it's a special case really - where something like [regtype=]23::TEXT - returns 'int4' as opposed to '23'). 
Also - making the cast expression recursive would complicate it w/o much benefit? happy to be told otherwise if you have a strong feeling about this.

2025-01-21 09:56 UTC, jarohen requested changes
this still seems a fair way off I'm afraid :slightly_frowning_face: 

I didn't see any tests for any of the added functionality - even if it doesn't fully support displaying tables yet (because of collate) I would have expected to see tests added for `operator.~` or visitPgCatalogResolveOid etc.

Could you land the pg_am change independently? this is an atomic change that can be added separately, and would make this PR much easier to read :slightly_smiling_face: :pray:

2025-01-21 09:56 UTC, jarohen commented on core/src/main/antlr/xtdb/antlr/Sql.g4
> +    | exprPrimary '::' schemaName '.' 'REGTYPE' '::' schemaName '.' 'TEXT' # PgCatalogResolveOid
> Also - making the cast expression recursive would complicate it w/o much benefit?

having two expressions in one rule is more complicated, we don't do this anywhere else - in a grammar, you decompose the syntax down into its constituent parts.

> happy to be told otherwise if you have a strong feeling about this.

yes please :pray:

2025-01-21 09:56 UTC, jarohen commented on core/src/main/clojure/xtdb/sql/plan.clj
> +    (.visitPostgresRegexPredicate this ctx))
presumably `operator` can take any kind of operator, not just regex?

2025-01-21 09:56 UTC, jarohen commented on core/src/main/clojure/xtdb/information_schema.clj
> +             ;; FIXME this should prolly be something else (arrow-HMT-handler?)
> probably you mean prolly? it's kind of like i18n

no it isn't, please fix it.

2025-01-21 09:56 UTC, jarohen commented on core/src/main/clojure/xtdb/sql/plan.clj
> +    (let [_rel-owner (.getText (.relOwner ctx))]
is this let-binding dead code? if so, could it be removed

2025-01-21 09:56 UTC, jarohen commented on core/src/main/clojure/xtdb/sql/plan.clj
> +    (.getText (.collation ctx)))
I doubt the right thing to do is return the collation part here, even if we're not planning to fully implement it. Once implemented, won't this expression return the `expr` string rather than the name of the collation?

tbh I'm surprised this doesn't break something else?

2025-01-21 09:56 UTC, jarohen commented on core/src/main/antlr/xtdb/antlr/Sql.g4
> +    | (schemaName '.')? 'PG_GET_USERBYID' '(' relOwner=columnReference ')' #PostgresGetUserbyidFunction
please make this casing consistent with the rest of the file: `PostgresGetUserByIdFunction`

2025-01-22 08:19 UTC, mpisanko commented
Closing as this started with supporting \d and then added quite a lot of stuff to support \d foo - but that is not implemented, so no point having all those changes hanging there. will submit another isolated PR

2025-01-22 08:19 UTC, closed without merging