Consistent map hashing, fixes #362
xtdb/xtdb pull request #474
Opened 2019-12-13 18:02 UTC by jarohen

A couple of changes from the reqmts in #362:
* SHA1 hashing maps without sorting them turned out to require hashing each value separately, rather than sorting-then-hashing, where you can just hash the whole map.
* because of how we actually use these hashes in practice, I don't think we need the backwards compatibility, nor the Kafka migration, nor the tool (although it'd no doubt be useful)

right. first, where do we use these hashes, and what properties do we need of them?

1. In the Kafka consumer, each message on the transaction log has a set of content-hashes, each message on the document log is keyed by the content-hash. The consumer waits for all the documents of a transaction to be in the object store before indexing the transaction
2/ In the KV indices, we look up AV and get EC (content-hash). we look up the content hash in the bitemp (EVtTtC) index to check whether it's current, and in the object store to get the underlying document - these three need to be consistent, and also consistent with the hashes in incoming queries/entity reqs. 

importantly, while the indexer does calculate the hashes of the eids/values, to insert into the indices, I don't think it re-calculates the document content-hash - it trusts the one that it gets in from Kafka.so, 

given we've got an index version bump going in anyway, we can assume that users are going to have to reindex their KV stores - which means that the new KV stores can be indexed using the consistent map-hashing. this means that the eid/value hashes in the updated AVEC/EVtTtC indices will match each other, and the query parameters. there'll be some old-style content-hashes in the 'C' fields, and some new-style, but old and new will both match with what's in the object store.

on Kafka, content-hashes don't need to match between transactions - so it's fine that we have old transactions with new in the same Kafka instance.

upshot is that we just need to ensure that, whenever we need to hash an object, we post-walk and sort all of the maps, so that they serialise consistently, and hence hash consistently. success :smile:

2019-12-13 19:25 UTC, hraberg requested changes

2019-12-13 19:25 UTC, hraberg commented on crux-core/src/crux/codec.clj
> +  (->> o (walk/postwalk (fn [o] (cond->> o (map? o) (into (sorted-map)))))))
This should probably be `instance? Map` as `map?` just checks for `IPeristentMap`? (Similar to how the change was done below for `id->buffer`.)

2019-12-14 15:25 UTC, hraberg approved these changes

2019-12-14 20:14 UTC, jarohen commented
thanks @hraberg :smile:

2019-12-16 13:00 UTC, refset commented
I think one issue might be that users could want to run a CAS against an old document version which would require recalculating the old hash, unless they retrieved and used the hash from the history APIs.

2019-12-18 17:05 UTC, merged