Aggregates bench results into one email
xtdb/xtdb pull request #690
Opened 2020-02-26 10:47 UTC by t-taylor

Fixes #683

2020-02-26 11:40 UTC, jarohen requested changes
hey gents - I'd be surprised if this one worked, I'm afraid. how're you testing this locally?

2020-02-26 11:40 UTC, jarohen commented on crux-bench/src/crux/bench/main.clj
> +       (reduce (fn [acc [node-type result]]
you're not using `acc` at all here, so I'd be surprised if this included all the results?

tbh, I suspect you don't need a `reduce` anyway - `reduce` is usually used when later elements need to access the results of iterating through earlier elements, whereas in this case you can probably combine them at the end?

2020-02-26 11:40 UTC, jarohen commented on crux-bench/src/crux/bench/main.clj
> +         (let [devices-results (devices/run-devices-bench node)
it looks like this `let` isn't yielding any value, so I'd be surprised if this worked?

2020-02-26 11:40 UTC, jarohen commented on crux-bench/src/crux/bench/main.clj
> +         (let [devices-results (devices/run-devices-bench node)
let's also try to split out the part that runs the bench vs the part that outputs to slack/email, it seems they're a little convoluted here. maybe the `let` could return the results out of the with-nodes, then we can process the results outside?

2020-02-26 14:15 UTC, t-taylor commented
> hey gents - I'd be surprised if this one worked, I'm afraid. how're you testing this locally?

Sorry James, it was meant to still be a draft at this stage. Github changes it back from draft to pr if you've written text in the pr message and then switched branch, which caught me out. I've refactored out the posting to slack per feedback now however

2020-02-28 17:26 UTC, jarohen requested changes
cheers - couple of stylistic points below but I like the way the bench runs are now completely decoupled from where we're outputting the results

2020-02-28 17:26 UTC, jarohen commented on crux-bench/src/crux/bench/main.clj
> +         (let [devices-results (doto (devices/run-devices-bench node)
I'd inline these three in the vector below - you're only using the bindings once and the names don't really add any clarity

2020-02-28 17:26 UTC, jarohen commented on crux-bench/src/crux/bench/main.clj
> +       (reduce (fn [acc [node-type result]]
you don't need the power of a `reduce` here, map + string/join is sufficient. I'd try to steer clear of `reduce` unless later values need the accumulator - as a reader, I need to reason about how the elements might interact with each other; with a `map`, I _know_ they can't.

2020-02-28 17:52 UTC, jarohen requested changes

2020-02-28 17:52 UTC, jarohen commented on crux-bench/src/crux/bench/watdiv_crux.clj
> -         (->query-result (rest watdiv-results))]
this returned the raw results so that the raw results were put into CloudWatch, the summarised results to Slack - let's preserve this behaviour

2020-02-28 18:29 UTC, merged