Generate javadoc on release
xtdb/xtdb pull request #692
Opened 2020-02-26 17:05 UTC by danmason

(Fix #530)

Generates javadocs for both the normal crux.api java files and the crux.api.alpha java files, then uploads them to S3 under the 'crux-doc' bucket.

2020-02-26 18:32 UTC, jarohen requested changes
looking good :) just the version in the path as mentioned on Slack, then should be good to go.

how's this getting permission to sync to S3, btw - we got some kind of CircleCI AWS user?

2020-02-27 10:50 UTC, danmason commented
Yeah, we have an IAM user called 'circleci-user', we also use it for deployment to AWS.

2020-02-27 15:48 UTC, jarohen approved these changes

2020-02-27 15:49 UTC, closed without merging

2020-02-27 15:50 UTC, jarohen commented
merged