Crux Data Browser - Entity State
xtdb/xtdb pull request #800
Opened 2020-04-17 13:09 UTC by danmason

Adds `_entity`, as per #788

2020-04-17 14:11 UTC, danmason commented
Failing build - Might need to move the muuntaja middleware into the `entity-state` itself, if possible

2020-04-17 14:42 UTC, jarohen requested changes
thanks Dan - few things to think about below. 

also, can't see a build for this commit?

2020-04-17 14:42 UTC, jarohen commented on crux-http-server/src/crux/http_server.clj
> +  (format
what will this do with nested structures?

2020-04-17 14:42 UTC, jarohen commented on crux-http-server/src/crux/http_server.clj
> +                                                       (wrap-format
this will wrap all the endpoints with this HTML formatter - that what we want?

2020-04-17 14:42 UTC, jarohen commented on crux-http-server/src/crux/http_server.clj
> +  (let [[_ encoded-eid] (re-find #"^/_entity/(.+)$" (req/path-info request))]
I'd say the time's come to start with a proper routing library - we've outgrown manually parsing out each individual value

2020-04-17 14:42 UTC, jarohen commented on crux-http-server/src/crux/http_server.clj
> +          entity-map (.entity db eid)]
advise using the Clojure API here, `(crux/entity db eid)`

2020-04-17 14:42 UTC, jarohen commented on crux-http-server/src/crux/http_server.clj
> +    (encode-to-output-stream [_ data charset]
the reason for a separate `encode-to-output-stream` (in addition to `encode-to-bytes`) is likely that the former's to be used for large streaming response bodies (which we will likely need for queries), the latter being sufficient for when the response fits in memory.

probably more of an issue when you implement `/_query`, so maybe this is fine for now

2020-04-20 12:56 UTC, jarohen commented on crux-http-server/src/crux/http_server.clj
> +  (let [[_ encoded-eid] (re-find #"^/_entity/(.+)$" (req/path-info request))]
as discussed, bringing this in as a separate change

2020-04-20 12:57 UTC, jarohen commented on crux-http-server/src/crux/http_server.clj
> +    (encode-to-output-stream [_ data charset]
yep, let's leave this for query

2020-04-20 13:14 UTC, merged