S3 doc-store, #810
xtdb/xtdb pull request #814
Opened 2020-04-22 16:13 UTC by jarohen

resolves #810

TODO:
- [ ] Config - discuss. There's a whole load of S3 options (where to get creds from, object encryption, etc) - should we/how should we expose these to users? Don't want to replicate the S3 API, but also don't want to prevent users using it because we don't expose the <x> config option.
- [ ] Tests - discuss. Could include this as part of API test, but would probably take a long time for not much benefit (and would need config/creds). Maybe we should have doc-store specific acceptance tests?
- [ ] README
- [ ] docs, blogs etc.

2020-04-22 17:01 UTC, jonpither requested changes

2020-04-22 17:01 UTC, jonpither commented on crux-s3/project.clj
> +(defproject juxt/crux-bench "derived-from-git"
should be crux-s3

2020-04-27 17:06 UTC, jonpither approved these changes

2020-04-30 09:43 UTC, hraberg approved these changes

2020-04-30 09:43 UTC, hraberg commented on crux-s3/src/crux/s3.clj
> +                               (reify S3Configurator))}
This could/should simply be `S3Configurator.` ctor.

2020-04-30 09:55 UTC, merged