Data browser - Styling changes, adding codemirror.
xtdb/xtdb pull request #899
Opened 2020-06-01 15:03 UTC by danmason

A number of changes by @luciodale - adding some code mirror editors, and some general styling improvements and fixes.

2020-06-22 10:27 UTC, luciodale commented on crux-http-server/src-cljs/crux/ui/codemirror.cljs
> +
This can go :)

2020-06-22 10:27 UTC, luciodale commented on crux-http-server/src-cljs/crux/ui/events.cljs
> +         current-storage (or (reader/read-string (.getItem js/window.localStorage "query")) [])
Maybe we should do this in a re-frame interceptor

2020-06-22 10:37 UTC, danmason commented on crux-http-server/src-cljs/crux/ui/codemirror.cljs
> +
We are using it, though?

2020-06-23 08:59 UTC, jarohen requested changes
Thanks gents :smile: 

As usual, I've only skimmed the CLJS/CSS side, assume you two have paired up on that? If not, happy to review more thoroughly.

Any chance we can serve the Lato font from the Google fonts CDN?

2020-06-24 08:07 UTC, danmason commented
Post our discussion/attempts at doing so, we decided on serving the fonts from the repo. Generally gone through and cleaned up the unused fonts, bringing the total number of font files added down to 16 rather than round 70.

2020-06-24 11:09 UTC, luciodale approved these changes

2020-06-26 10:16 UTC, merged